name: HelloBot

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:

    steps:
    - name: HelloBot
      run: |
        npm ci
        npm start
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
